#!/usr/bin/env python3
"""Architecture bake-off V1 — run identical training on same data.

For each architecture trains on the same (X_lob, X_feat, y, target_pnl)
with identical hyperparameters and reports leaderboard.

Usage:
    python scripts/bakeoff_v1.py --cache <training_cache.npz> \
        --archs transformer patchtst --epochs 40

Reads a cache produced by `trainer.build_samples` (or a fixture generated by
tests). Outputs a JSON leaderboard + per-model state_dicts under `runs/`.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.models import PatchTST, PatchTSTConfig  # noqa: E402
from src.models.train import train_generic  # noqa: E402
from src.teacher import MultiStreamTransformer, TeacherConfig  # noqa: E402


def build_factory(arch: str):
    """Return model_factory(num_feat) → nn.Module for the given arch name."""
    if arch == "transformer":
        def _f(num_feat: int):
            return MultiStreamTransformer(num_feat=num_feat, cfg=TeacherConfig())
        return _f, "transformer"
    if arch == "patchtst":
        def _f(num_feat: int):
            return PatchTST(num_feat=num_feat, cfg=PatchTSTConfig())
        return _f, "patchtst"
    raise ValueError(f"unknown arch: {arch}")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--cache", required=True,
                   help="NPZ with X_lob, X_feat, y, target_pnl")
    p.add_argument("--archs", nargs="+", required=True)
    p.add_argument("--epochs", type=int, default=40)
    p.add_argument("--batch-size", type=int, default=256)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--out", default="runs/bakeoff_v1")
    p.add_argument("--seed", type=int, default=42)
    args = p.parse_args()

    data = np.load(args.cache, mmap_mode="r", allow_pickle=False)
    X_lob = data["X_lob"]
    X_feat = data["X_feat"]
    y = data["y"]
    target_pnl = data["target_pnl"]
    print(f"[bakeoff] loaded {len(y)} samples: X_lob {X_lob.shape} X_feat {X_feat.shape}")

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    leaderboard = []
    for arch in args.archs:
        factory, tag = build_factory(arch)
        print(f"\n==== {tag} ====")
        t0 = time.time()
        model, metrics = train_generic(
            factory, X_lob, X_feat, y, target_pnl,
            batch_size=args.batch_size, epochs=args.epochs, lr=args.lr,
            seed=args.seed, tag=tag,
        )
        dt = time.time() - t0
        torch.save(model.state_dict(), out_dir / f"{tag}.pt")
        row = {
            "arch": tag,
            "best_bal_acc": metrics["best_bal_acc"],
            "params_M": metrics["params_M"],
            "train_seconds": dt,
            "epochs_run": len(metrics["history"]),
        }
        leaderboard.append(row)
        print(f"[bakeoff] {tag} done — bal_acc={row['best_bal_acc']:.4f} "
              f"params={row['params_M']:.2f}M time={dt:.0f}s")

    leaderboard.sort(key=lambda r: -r["best_bal_acc"])
    with (out_dir / "leaderboard.json").open("w") as f:
        json.dump({"rows": leaderboard, "args": vars(args)}, f, indent=2)

    print("\n=== Leaderboard ===")
    for r in leaderboard:
        print(f"  {r['arch']:12s}  bal_acc={r['best_bal_acc']:.4f}  "
              f"params={r['params_M']:.2f}M  time={r['train_seconds']:.0f}s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
