#!/usr/bin/env python3
"""Architecture bake-off V1 — run identical training on same data.

For each architecture trains on the same (X_lob, X_feat, y, target_pnl)
with identical hyperparameters and reports leaderboard.

Usage:
    python scripts/bakeoff_v1.py --cache <training_cache.npz> \
        --archs transformer patchtst --epochs 40

Reads a cache produced by `trainer.build_samples` (or a fixture generated by
tests). Outputs a JSON leaderboard + per-model state_dicts under `runs/`.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.models import (  # noqa: E402
    PatchTST, PatchTSTConfig,
    MambaClassifier, MambaModelConfig,
    TCNClassifier, TCNConfig,
    ChronosClassifier, ChronosAdapterConfig,
)
from src.models.train import train_generic  # noqa: E402
from src.teacher import MultiStreamTransformer, TeacherConfig  # noqa: E402


def build_factory(arch: str):
    """Return model_factory(num_feat) → nn.Module for the given arch name."""
    if arch == "transformer":
        def _f(num_feat: int):
            return MultiStreamTransformer(num_feat=num_feat, cfg=TeacherConfig())
        return _f, "transformer"
    if arch == "patchtst":
        def _f(num_feat: int):
            return PatchTST(num_feat=num_feat, cfg=PatchTSTConfig())
        return _f, "patchtst"
    if arch == "mamba":
        def _f(num_feat: int):
            return MambaClassifier(num_feat=num_feat, cfg=MambaModelConfig())
        return _f, "mamba"
    if arch == "tcn":
        def _f(num_feat: int):
            return TCNClassifier(num_feat=num_feat, cfg=TCNConfig())
        return _f, "tcn"
    if arch == "chronos_bolt_small":
        def _f(num_feat: int):
            return ChronosClassifier(num_feat=num_feat, cfg=ChronosAdapterConfig(
                model_name="amazon/chronos-bolt-small", freeze_encoder=True))
        return _f, "chronos_bolt_small"
    if arch == "chronos_bolt_tiny":
        def _f(num_feat: int):
            return ChronosClassifier(num_feat=num_feat, cfg=ChronosAdapterConfig(
                model_name="amazon/chronos-bolt-tiny", freeze_encoder=True))
        return _f, "chronos_bolt_tiny"
    raise ValueError(f"unknown arch: {arch}")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--cache", required=True,
                   help="NPZ with X_lob, X_feat, y, target_pnl")
    p.add_argument("--archs", nargs="+", required=True)
    p.add_argument("--epochs", type=int, default=40)
    p.add_argument("--batch-size", type=int, default=256)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--out", default="runs/bakeoff_v1")
    p.add_argument("--seed", type=int, default=42)
    args = p.parse_args()

    data = np.load(args.cache, mmap_mode="r", allow_pickle=False)
    X_lob = data["X_lob"]
    X_feat = data["X_feat"]
    y = data["y"]
    target_pnl = data["target_pnl"]
    print(f"[bakeoff] loaded {len(y)} samples: X_lob {X_lob.shape} X_feat {X_feat.shape}")

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    leaderboard = []
    stacker_inputs = []  # list of (tag, val_softmax) for optional stacker fit
    y_val_ref = None
    X_feat_val_ref = None
    for arch in args.archs:
        factory, tag = build_factory(arch)
        print(f"\n==== {tag} ====")
        t0 = time.time()
        model, metrics = train_generic(
            factory, X_lob, X_feat, y, target_pnl,
            batch_size=args.batch_size, epochs=args.epochs, lr=args.lr,
            seed=args.seed, tag=tag,
        )
        dt = time.time() - t0
        torch.save(model.state_dict(), out_dir / f"{tag}.pt")
        np.save(out_dir / f"{tag}_val_softmax.npy", metrics["val_softmax"])
        stacker_inputs.append((tag, metrics["val_softmax"]))
        y_val_ref = metrics["y_val"]
        X_feat_val_ref = metrics["X_feat_val"]
        row = {
            "arch": tag,
            "best_bal_acc": metrics["best_bal_acc"],
            "params_M": metrics["params_M"],
            "train_seconds": dt,
            "epochs_run": len(metrics["history"]),
        }
        leaderboard.append(row)
        print(f"[bakeoff] {tag} done — bal_acc={row['best_bal_acc']:.4f} "
              f"params={row['params_M']:.2f}M time={dt:.0f}s")

    # --- Stacker (level-2 meta-learner) ---
    if len(stacker_inputs) >= 2:
        from src.models import train_stacker
        print(f"\n==== stacker ({len(stacker_inputs)} primaries) ====")
        softs = [s for _, s in stacker_inputs]
        stacker, s_metrics = train_stacker(softs, y_val_ref, X_feat=X_feat_val_ref)
        import joblib
        joblib.dump(stacker, out_dir / "stacker.joblib")
        s_metrics["primaries"] = [t for t, _ in stacker_inputs]
        print(f"[bakeoff] stacker — val_bal_acc={s_metrics['val_bal_acc']:.4f} "
              f"val_acc={s_metrics['val_acc']:.4f}")
        leaderboard.append({
            "arch": "stacker",
            "best_bal_acc": s_metrics["val_bal_acc"],
            "params_M": float("nan"),
            "train_seconds": 0.0,
            "epochs_run": 0,
            "primaries": s_metrics["primaries"],
        })
        with (out_dir / "stacker_metrics.json").open("w") as f:
            json.dump(s_metrics, f, indent=2, default=float)

    leaderboard.sort(key=lambda r: -r["best_bal_acc"])
    with (out_dir / "leaderboard.json").open("w") as f:
        json.dump({"rows": leaderboard, "args": vars(args)}, f, indent=2, default=str)

    print("\n=== Leaderboard ===")
    for r in leaderboard:
        print(f"  {r['arch']:12s}  bal_acc={r['best_bal_acc']:.4f}  "
              f"params={r['params_M']:.2f}M  time={r['train_seconds']:.0f}s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
